name: Feature
description: 새로운 기능 추가 및 개선
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        <!-- 작성 이전에 동일 이슈가 존재하는지 파악해주세요. -->
        *이슈만 보고 기능과 작업을 충분히 이해할 수 있도록 충실히 작성하겠습니다.*
  - type: textarea
    id: summary
    attributes:
      label: 요약
      description: |
        추가되는 기능에 대해 1~2줄 정도의 간결한 설명을 추가해주세요.
        기능의 의도에 대해 서술하는 것 역시 권장됩니다.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: 상세
    validations:
      required: true
  - type: textarea
    id: todolist
    attributes:
      label: 세부 구현 리스트
      description: |
        기능 구현을 위해 필요한 작업 리스트를 서술하세요.
        다른 사람이 이 리스트만 보고도 개괄적인 작업 흐름에 대해 알 수 있도록 작성해야 합니다.
      value: |
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: true
  - type: checkboxes
    id: environments
    attributes:
      label: 환경
      description: 해당하는 환경을 체크해주세요.
      options:
        - label: MacOS
        - label: Windows
  - type: textarea
    id: reference
    attributes:
      label: 레퍼런스
      description: |
        참고할 만한 문서가 있다면 첨부해주세요.
      value: |
        - Notion:
        - TeamChat:
        - Figma: 
        - Other Issues: 
    validations:
      required: true
