name: Feature
description: 새로운 기능 추가 및 개선
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        <!-- 작성 이전에 동일 이슈가 존재하는지 파악해주세요. -->
        이슈만 보고 기능을 충분히 이해할 수 있도록 충실히 작성하겠습니다.
  - type: textarea
    id: summary
    attributes:
      label: 요약
      description: |
        추가되는 기능에 대해 1~2줄 정도의 간결한 설명을 추가해주세요.
        기능의 의도에 대해 서술하는 것 역시 권장됩니다.
    validations:
      required: true
